//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirVentsCadWpf.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBomTableService")]
    public interface IBomTableService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/PathById", ReplyAction="http://tempuri.org/IBomTableService/PathByIdResponse")]
        string PathById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/PathById", ReplyAction="http://tempuri.org/IBomTableService/PathByIdResponse")]
        System.Threading.Tasks.Task<string> PathByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/PathByNameAsm", ReplyAction="http://tempuri.org/IBomTableService/PathByNameAsmResponse")]
        string PathByNameAsm(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/PathByNameAsm", ReplyAction="http://tempuri.org/IBomTableService/PathByNameAsmResponse")]
        System.Threading.Tasks.Task<string> PathByNameAsmAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/AsmNames", ReplyAction="http://tempuri.org/IBomTableService/AsmNamesResponse")]
        string[] AsmNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/AsmNames", ReplyAction="http://tempuri.org/IBomTableService/AsmNamesResponse")]
        System.Threading.Tasks.Task<string[]> AsmNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/Bom", ReplyAction="http://tempuri.org/IBomTableService/BomResponse")]
        BomPartList.BomPartListClass.BomCells[] Bom(int type, string assemblyPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/Bom", ReplyAction="http://tempuri.org/IBomTableService/BomResponse")]
        System.Threading.Tasks.Task<BomPartList.BomPartListClass.BomCells[]> BomAsync(int type, string assemblyPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/BomParts", ReplyAction="http://tempuri.org/IBomTableService/BomPartsResponse")]
        BomPartList.BomPartListClass.BomCells[] BomParts(string assemblyPath, string pdmBaseName, string userName, string password, string constring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBomTableService/BomParts", ReplyAction="http://tempuri.org/IBomTableService/BomPartsResponse")]
        System.Threading.Tasks.Task<BomPartList.BomPartListClass.BomCells[]> BomPartsAsync(string assemblyPath, string pdmBaseName, string userName, string password, string constring);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBomTableServiceChannel : AirVentsCadWpf.ServiceReference1.IBomTableService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BomTableServiceClient : System.ServiceModel.ClientBase<AirVentsCadWpf.ServiceReference1.IBomTableService>, AirVentsCadWpf.ServiceReference1.IBomTableService {
        
        public BomTableServiceClient() {}
        
        public BomTableServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {}
        
        public BomTableServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {}
        
        public BomTableServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {}
        
        public BomTableServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {}
        
        public string PathById(int id) {return base.Channel.PathById(id);}
        
        public System.Threading.Tasks.Task<string> PathByIdAsync(int id) {return base.Channel.PathByIdAsync(id);}
        
        public string PathByNameAsm(string name) {return base.Channel.PathByNameAsm(name);}
        
        public System.Threading.Tasks.Task<string> PathByNameAsmAsync(string name) {return base.Channel.PathByNameAsmAsync(name);}
        
        public string[] AsmNames() {return base.Channel.AsmNames();}
        
        public System.Threading.Tasks.Task<string[]> AsmNamesAsync() {return base.Channel.AsmNamesAsync();}
        
        public BomPartList.BomPartListClass.BomCells[] Bom(int type, string assemblyPath) {return base.Channel.Bom(type, assemblyPath);}
        
        public System.Threading.Tasks.Task<BomPartList.BomPartListClass.BomCells[]> BomAsync(int type, string assemblyPath) {return base.Channel.BomAsync(type, assemblyPath);}
        
        public BomPartList.BomPartListClass.BomCells[] BomParts(string assemblyPath, string pdmBaseName, string userName, string password, string constring) {
            return base.Channel.BomParts(assemblyPath, pdmBaseName, userName, password, constring);
        }
        
        public System.Threading.Tasks.Task<BomPartList.BomPartListClass.BomCells[]> BomPartsAsync(string assemblyPath, string pdmBaseName, string userName, string password, string constring) {
            return base.Channel.BomPartsAsync(assemblyPath, pdmBaseName, userName, password, constring);
        }
    }
}
